version: "3"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - PASSWORD=${PW} #optional
      #- HASHED_PASSWORD= #optional
      #- SUDO_PASSWORD=password #optional
      #- SUDO_PASSWORD_HASH= #optional
      #- PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspaces #optional
    volumes:
      - ./workspaces:/config/workspaces
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      - reverseproxy
networks:
  reverseproxy:
    external: true

