version: "3"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      # - PASSWORD= #optional
      - HASHED_PASSWORD=$$argon2i$$v=19$$m=4096,t=3,p=1$$XDPe/B9p08NnK78aXsUYQg$$Gw+RyuUF1DBZ9PpG7o2eoonKciL8UBhN7F0xcrDgy10
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      # - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./workspaces:/config/workspaces
    # ports:
    #   - 8443:8443
    restart: unless-stopped
    networks:
      - reverseproxy
networks:
  reverseproxy:
    external: true

