version: "3.7"
services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    networks:
      - reverseproxy
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - $PWD/caddy/config/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data:
    external: true
  caddy_config:
networks:
  reverseproxy:
    external: true

